# Generated by Django 4.2.1 on 2023-08-29 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Suggestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date_time", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Creating suggestion",
                "verbose_name_plural": "Creating suggestions",
                "ordering": ("-date_time", "title"),
            },
        ),
    ]
